version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"

  dynamodb-init:
      image: amazon/aws-cli
      container_name: dynamodb-init
      depends_on:
        - dynamodb-local
      volumes:
        - ./dynamodb-init:/dynamodb-init
      environment:
        # DynamoDB local requires credentials, but they can be fake
        AWS_REGION: "us-west-2"
        AWS_ACCESS_KEY_ID: local
        AWS_SECRET_ACCESS_KEY: local
      entrypoint: ["/bin/sh", "-c"]
      command: "/dynamodb-init/init-dynamodb-script.sh"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local