CREATE TABLE IF NOT EXISTS COMMENT (
    id VARCHAR(36) PRIMARY KEY,
    content TEXT NOT NULL,
    post_id VARCHAR(36) NOT NULL,
    CONSTRAINT fk_post FOREIGN KEY(post_id) REFERENCES POST(id) ON DELETE CASCADE
);