spring:
  docker:
    compose:
      file: "../docker-compose.yml"
      output:
        read: all
  application:
    name: dualDBDemo
    storage: 
      engine: postgres # Or 'dynamodb'
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    bootstrap: 
  threads: 
    virtual:
      enabled: true
  task:
    execution:
      thread-name-prefix: dual-write-vt- 
      shutdown:
        await-termination: true          
        await-termination-period: 30s

logging:
  level:
    org.springframework.boot.docker.compose: DEBUG
